name: Boss Farm Raid Script

on:
  workflow_dispatch:

jobs:
  boss_farm_raid:
    runs-on: ubuntu-latest
    if: github.actor == 'Ddkotl'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install
      - run: npm run build
      - run: npm run boss_farm_raid
