name: Send Virus Script

on:
  workflow_dispatch:

jobs:
  send-virus-weekday:
    runs-on: ubuntu-latest
    if: github.actor == 'Ddkotl' 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install
      - run: npm run build
      - run: npm run send_virus
