name: Send Virus Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * 1-6"
    - cron: "1 21 * * 0"

jobs:
  send-virus-weekday:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install
      - run: npm run build
      - run: npm run send_virus
